


WITH init_query AS
(
	SELECT A.NAME_OF_SCHOOL, A.COMMUNITY_AREA_NAME,
	A.AVERAGE_STUDENT_ATTENDANCE, A.AVERAGE_TEACHER_ATTENDANCE,
	A.COMMUNITY_AREA_NUMBER, B.HARDSHIP_INDEX 
	FROM CHICAGO_PUBLIC_SCHOOLS A LEFT JOIN CENSUS_DATA B
	ON A.COMMUNITY_AREA_NUMBER = B.COMMUNITY_AREA_NUMBER
)
SELECT * FROM init_query
WHERE hardship_index = 98
;

WITH init_query AS
(
	SELECT A.CASE_NUMBER, A.PRIMARY_TYPE, 
	B.COMMUNITY_AREA_NAME, A.LOCATION_DESCRIPTION 
	FROM CHICAGO_CRIME_DATA A LEFT JOIN CENSUS_DATA B
	ON A.COMMUNITY_AREA_NUMBER = B.COMMUNITY_AREA_NUMBER
)
SELECT* FROM init_query
WHERE LOCATION_DESCRIPTION LIKE '%SCHOOL%';

SELECT * FROM CHICAGO_PUBLIC_SCHOOLS LIMIT 20;
 
 
CREATE VIEW view1(School_Name, Safety_Rating, Family_Rating, 
	Environment_Rating, Instruction_Rating, 
	Leaders_Rating, Teachers_Rating) 
AS
SELECT NAME_OF_SCHOOL, Safety_Icon, Family_Involvement_Icon,
	Environment_Icon, Instruction_Icon, Leaders_Icon, Teachers_Icon
FROM CHICAGO_PUBLIC_SCHOOLS;


SELECT * FROM view1 LIMIT;


SELECT SCHOOL_NAME, LEADERS_RATING FROM view1;


SELECT school_id, leaders_score, LEADERS_ICON FROM CHICAGO_PUBLIC_SCHOOLS LIMIT 200;
 
--#SET TERMINATOR @
CREATE PROCEDURE UPDATE_LEADERS_SCORE
(IN in_School_ID INTEGER, IN in_Leader_Score INTEGER)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN 
	UPDATE CHICAGO_PUBLIC_SCHOOLS
	SET LEADERS_SCORE = in_Leader_Score
	WHERE SCHOOL_ID = in_School_ID;
	IF in_Leader_Score > 0 AND in_Leader_Score < 20 THEN
		UPDATE CHICAGO_PUBLIC_SCHOOLS
		SET Leaders_Icon = 'Very weak'
		WHERE SCHOOL_ID = in_School_ID;
	ELSEIF in_Leader_Score < 40 THEN
		UPDATE CHICAGO_PUBLIC_SCHOOLS
		SET Leaders_Icon = 'Weak'
		WHERE SCHOOL_ID = in_School_ID; 
	ELSEIF in_Leader_Score < 60 THEN
		UPDATE CHICAGO_PUBLIC_SCHOOLS
		SET Leaders_Icon = 'Average'
		WHERE SCHOOL_ID = in_School_ID;
	ELSEIF in_Leader_Score < 80 THEN
		UPDATE CHICAGO_PUBLIC_SCHOOLS
		SET Leaders_Icon = 'Strong'
		WHERE SCHOOL_ID = in_School_ID; 
	ELSEIF in_Leader_Score < 100 THEN
		UPDATE CHICAGO_PUBLIC_SCHOOLS
		SET Leaders_Icon = 'Very Strong'
		WHERE SCHOOL_ID = in_School_ID;
	ELSE 
		ROLLBACK WORK;
	COMMIT WORK;
	END IF;
END
@

--#SET TERMINATOR ;
ALTER TABLE CHICAGO_PUBLIC_SCHOOLS
ALTER COLUMN LEADERS_ICON SET DATA TYPE VARCHAR(20);

CALL UPDATE_LEADERS_SCORE(610038,50);

SELECT SCHOOL_ID, LEADERS_SCORE, LEADERS_ICON 
FROM CHICAGO_PUBLIC_SCHOOLS
WHERE SCHOOL_ID = 610038;
 
 
 
 
 
CALL UPDATE_LEADERS_SCORE(610038,38);
 
SELECT SCHOOL_ID, LEADERS_SCORE, LEADERS_ICON 
FROM CHICAGO_PUBLIC_SCHOOLS
WHERE SCHOOL_ID = 610038;
 
CALL UPDATE_LEADERS_SCORE(610038,101);
 
SELECT SCHOOL_ID, LEADERS_SCORE, LEADERS_ICON 
FROM CHICAGO_PUBLIC_SCHOOLS
WHERE SCHOOL_ID = 610038;
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 